---
abstract: 'Make your html more iPhone friendly'
author:
  - 'Patrick Donelan <pat@patspam.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-iPhone
requires:
  Digest::MD5: 0
  File::Find: 0
  File::Slurp: 0
  File::Temp: 0
  HTML::DOM: 0
  HTML::Tidy: 0
  HTTP::Request::Common: 0
  Plack::Builder: 0
  Plack::Middleware: 0
  Plack::Test: 0
  Plack::Util::Accessor: 0
  Test::More: 0
  parent: 0
resources:
  repository: http://github.com/pdonelan/Plack-Middleware-iPhone
version: 1.100830
